[env]
TERM = "xterm-256color"

[scrolling]
history = 10000

# [colors.normal]
# blue = "#b59a74"
# green = "#118822"
# white = "#ffffff"

[colors.primary]
# mf era?
# background = "#09122e"
# background = "#0a1533"
# background = "#0e1b42"

# background = "#131e26" # green from focus editor
# pf era 
# background = "#00001A"

# background = "#010105"
# background = "#555555"

[debug]
log_level = "Info"
persistent_logging = true
print_events = true

[font]
size = 12.0
builtin_box_drawing = true


[font.normal]
family = "JetBrainsMono Nerd Font" 
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font" 
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font" 
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font" 
style = "Bold Italic"

[font.offset]
# y = 2

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "p"
mods = "Alt"

[terminal.shell]
args = ["--login"]
program = "/usr/bin/bash"

[general]
import = ["~/.config/alacritty/themes/themes/kitty.toml"]

[window]
opacity = 0.9
blur = true 

[terminal]

